spring.application.name=medicurex-pharmacy-service
server.port=8085

spring.datasource.url=${PHARMACY_DB_URL:jdbc:mysql://localhost:3306/medicurex_pharmacy?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:3945}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

spring.jackson.default-property-inclusion=non_null
spring.jackson.serialization.write-dates-as-timestamps=false

app.jwt.secret=${JWT_SECRET:1e21b38316d34ecb0b1fd7d10d7b92478aaa5c2ca4c70f1dbeaef51b69967ffe}

eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never
management.info.env.enabled=true
info.app.name=${spring.application.name}
info.app.description=MediCurex Pharmacy Service
